services:
  - type: web
    name: email-alerts-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: BREVO_API_KEY
        sync: false
      - key: REDIS_ENABLED
        value: "False"
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.12.3"
