"""initial migration

Revision ID: fcc8fca860ca
Revises: 
Create Date: 2026-09-08 11:40:24.546732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcc8fca860ca'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracked_emails',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sender_id', sa.String(length=100), nullable=False),
    sa.Column('tracking_token', sa.String(length=64), nullable=False),
    sa.Column('recipient_email', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('open_count', sa.Integer(), nullable=False),
    sa.Column('click_count', sa.Integer(), nullable=False),
    sa.Column('first_opened_at', sa.DateTime(), nullable=True),
    sa.Column('last_opened_at', sa.DateTime(), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tracked_emails_recipient_email'), 'tracked_emails', ['recipient_email'], unique=False)
    op.create_index(op.f('ix_tracked_emails_sender_id'), 'tracked_emails', ['sender_id'], unique=False)
    op.create_index(op.f('ix_tracked_emails_tracking_token'), 'tracked_emails', ['tracking_token'], unique=True)
    op.create_table('click_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tracked_email_id', sa.String(length=36), nullable=False),
    sa.Column('target_url', sa.String(length=2048), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=1000), nullable=True),
    sa.Column('device_type', sa.String(length=50), nullable=False),
    sa.Column('clicked_at', sa.DateTime(), nullable=False),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['tracked_email_id'], ['tracked_emails.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_click_events_clicked_at'), 'click_events', ['clicked_at'], unique=False)
    op.create_index(op.f('ix_click_events_tracked_email_id'), 'click_events', ['tracked_email_id'], unique=False)
    op.create_table('open_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tracked_email_id', sa.String(length=36), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=1000), nullable=True),
    sa.Column('device_type', sa.String(length=50), nullable=False),
    sa.Column('client_name', sa.String(length=100), nullable=True),
    sa.Column('os_name', sa.String(length=100), nullable=True),
    sa.Column('is_bot', sa.Boolean(), nullable=False),
    sa.Column('is_proxy', sa.Boolean(), nullable=False),
    sa.Column('proxy_type', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=False),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['tracked_email_id'], ['tracked_emails.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_open_events_opened_at'), 'open_events', ['opened_at'], unique=False)
    op.create_index(op.f('ix_open_events_tracked_email_id'), 'open_events', ['tracked_email_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_open_events_tracked_email_id'), table_name='open_events')
    op.drop_index(op.f('ix_open_events_opened_at'), table_name='open_events')
    op.drop_table('open_events')
    op.drop_index(op.f('ix_click_events_tracked_email_id'), table_name='click_events')
    op.drop_index(op.f('ix_click_events_clicked_at'), table_name='click_events')
    op.drop_table('click_events')
    op.drop_index(op.f('ix_tracked_emails_tracking_token'), table_name='tracked_emails')
    op.drop_index(op.f('ix_tracked_emails_sender_id'), table_name='tracked_emails')
    op.drop_index(op.f('ix_tracked_emails_recipient_email'), table_name='tracked_emails')
    op.drop_table('tracked_emails')
    # ### end Alembic commands ###
